name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version being released (pom.xml files will be updated) - leave empty for Maven default'
        required: false
        type: string
        default: ''
      netty:
        description: 'The version range to use for the Netty Core dependencies - will use value from pom.xml if empty'
        required: false
        type: string
        default: ''
      java-version:
        description: 'The version of Java to use for building'
        required: false
        type: string
        default: '11'

jobs:
  Release:
    uses: netty-contrib/.github/.github/workflows/release.yml@main
    with:
      version: ${{ inputs.version }}
      netty: ${{ inputs.netty }}
      java-version: ${{ inputs.java-version }}
    secrets: inherit
